@extends('frontend.layouts.app')

@section('page.title', 'Garib Nawaz Online Academy')

@section('page.description', 'Seedling & Associates is one of the best law firms in Delhi, India. We provide legal assistance for startups, FDI, Property law, IP, and more')

@section('page.type', 'website')

@section('page.content')


<section class="innertitle aboutus">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="inner_titles text-center">Terms & Conditions</h4>
                <nav aria-label="breadcrumb" class="breadcrumb mb-0">
                    <ol class="breadcrumb d-flex justify-content-center mb-0">
                        <li class="breadcrumb-item"><a href="index.php">Home</a></li>
                        <li class="breadcrumb-item">Term & Condition</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>

 <section class="content-terms pt-5 pb-5">
   <div class="container">
     <div class="row">
       <p> This document is an electronic record as understood under the provisions the of Information Technology Act, 2000 and rules made there under or under any statutory modification or re-enactment there of pertaining to electronic records. This electronic record is generated by a computer system and does not require any physical or digital signatures. </p>
       <p> This document is published in compliance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 and Information Technology (Guidelines for Intermediaries And Digital Media Ethics Code) Rules 2021 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of GNOA, including mobile applications related there to (hereinafter referred to as “Platform”). This Platform is owned by Faizane Madina Dawateislami India 50,Tantanpura Street Khadak Police Chowki Mumbai 400009 Maharshtra</p>
       <p> For the purpose of these Terms of Use, wherever the context so requires “You” or “User” shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. The term “We”, “Us”, “Our” shall mean. GNOA. If you transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with, GNOA and these terms and conditions constitute your binding obligations, with GNOA. </p>
       <p> These rules and regulations will be updated periodically. It is Your responsibility to review these Terms of Use periodically for updates/changes. Your continued use of the platform following the posting of changes will mean that You accept and agree on revisions. </p>
       <h5 class="mt-2">Membership Eligibility</h5>
       <p>Transaction on the Platform is available only to persons who can enter into legally binding contracts under Indian Contract Act, 1872. Persons who are “incompetent to contract” within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/ permission of a parent or a legal guardian. </p>
       <h5 class="mt-4">Account and Registration Obligations</h5>
       <p>“Your Information” as defined under the provisions of The Information Technology Act, 2000 is any information you provide to us in the registration, purchasing or listing process, in the feedback area or through any email feature. We will protect Your Information in accordance with our Privacy Policy. If you use the Site, you are responsible for maintaining the confidentiality of Your Account and Password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under Your Account or Password. GNOA or its affiliate shall not be liable to any person for any loss or damage which may be suffered by you as a result of any failure on your part to protect your password or account.</p>
       <p>If you share or allow others to have access to your account on the Platform (“Account”), by creating separate profiles under Your Account, or otherwise, Your Account information will become accessible to others. You shall be solely liable and responsible for all the activities undertaken under Your Account, and any consequences there from. </p>
       <p>The Information collected from a User for registration on the sight shall be retained for a period as mandated under the law after cancellation or withdrawal of registration by the user, as the case may be. </p>
       <h5 class="mt-3">You also agree to:</h5>
       <p>Provide true, accurate, current, and complete information about yourself as prompted by GNOA the registration form. Maintain and promptly update and keep it true, accurate, current, and complete. If you provide any information that is untrue, inaccurate, incomplete, or not current or if GNOA has reasonable grounds to suspect that such information is untrue, inaccurate, and not current or not in accordance with this User Agreement, GNOA has the right to indefinitely suspend or terminate your membership and refuse to provide you with access to the Site. </p>
       <p>In case of non -compliance with rules and regulations of this User Agreement and Private Policy. – GNOA shall have the right to immediately terminate the access or usage rights of the User to the computer resource and shall remove non-compliant information. </p>
       <h5 class="mt-3">Damage Claims or Shortages Important Notice</h5>
       <p>Any claims for damage and/or shortages MUST be reported in 24 hours from the receipt there of without exception. You must check your deliveries upon receipt. You agree to our Return Policy with the acceptance of these Terms of Use. </p>
       <h5 class="mt-3">Product Policy</h5>
       <p>GNOA does its best to ensure that the information viewed on our website is as accurate and error-free. GNOA accepts no liability for any errors or omissions, whether on behalf of itself or third parties. We do not warrant the product descriptions, and all other content of this website to be entirely accurate, complete, reliable, current, or error-free. We collect the information about the products from Amazon. after a telephonic confirmation via their customer care number. Additionally, barring any pricing inaccuracies, items in your shopping cart would always reflect the most recent price, which will be displayed on the item’s product detail page. Please note that this price may differ from the price shown for the item when you first place it in your cart. Prices are often changed by the respective company/sellers without prior information and will be charged accordingly. Images/visuals shown are for representation purposes only and we do not undertake any changes in MRP by manually mentioning the products. All the MRP are printed by the respective sellers only. We are the only service providers of the products ect.. listed on the website GNOA shall specify as far as possible and practicable, details about sellers offering products and services, the names of their business, registration details, geographic address, consumer care number, rating or other aggregated feedback about such seller and any other information necessary for enabling the Users to make an informed decision at the pre-purchase stage. GNOA however does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc) of any of its sellers. You are advised to independently verify the bona fides of any particular seller that You choose to deal with on the Platform and use Your best judgment on that behalf. GNOA is not responsible for the unsatisfactory or delayed performance of services or damages or delays as a result of products that are out of stock, unavailable, or back-ordered. With respect to items sold by GNOA, we cannot confirm the price of an item until you place an order. Despite our best efforts, a small number of the items in our catalog or on our website may be mispriced. In the event of a pricing inaccuracy, we will proceed at our discretion as follows:</p>
       <ul class="product-li">
         <li>If An Item’s Correct Price Is Lower Than Our Stated Price, We Will Charge The Lower Amount And Ship The Item To You.</li>
         <li>If An Item’s Correct Price Is Higher Than Our Stated Price, We Will Take One Of The Following Actions:</li>
         <li>Your Order Will Be Held, And We Will Attempt To Contact You For Further Instructions Regarding You Order</li>
         <li>Your Order Will Be Cancelled, And We Will Notify You Of The Cancellation Immediately With A Full Refund.</li>
       </ul>
       <h5 class="mt-3">Country of Origin</h5>
       <p>In deference to Prime Minister’s vision of “Atmanirbhar Bharat” and “Make in India” specifying the Country of Origin (“COO“), the majority of products sold on GNOA are of companies of Indian origin. Products / Brands may be imported by the respective Sellers. We strictly deal through the Authorized Company Distribution Network / Companies respectively. We do not directly Import/Export/Trade beyond the boundaries of India. Source:https://www.mondaq.com/india/international-trade-investment/968240/country-of-origin-to-be-specified-on-e-commerce-websites-for-product-listings </p>
       <!-- <h5 class="mt-3">Shipping Policy</h5>
       <p>We take utmost care in shipping Your products in association with our logistics partner {coming soon}. In order to make all procedures smooth and easy for delivery, it will take 3 – 5 working days for your order to be dispatched through our logistics partner. Ordinarily, our shipping charges are as follows: </p>
       <h5 class="mt-3">Charges:</h5>
       <ul class="product-li">
         <li>Weight Local Delivery BMC Limits (Mumbai)</li>
         <li>Base 0.1 to 1 kg 50.00</li>
         <li>Additional Every 1 kg 18.00</li>
       </ul>
       <h5 class="mt-4">Dispatch Delivery Schedule</h5>
       <p>Local (BMC/NON-BMC Limits): Up to 3 – 4 working days Rest of India: Up to 5 working days.</p> -->
       <h5 class="mt-3">Credit Card Details</h5>
       <p>You agree, understand and confirm that the credit card details provided by you for availing of services on GNOA will be correct and accurate and you shall not use the credit card which is not lawfully owned by you. You further agree and undertake to provide the correct and valid credit card details to GNOA. Further the said information will not be utilized or shared by GNOA with any of the third parties unless required for fraud verifications or by law, regulation or court order. </p>
       <p>GNOA will not be liable for any credit card fraud. The liability for use of a card fraudulently will be on You and the onus to ‘prove otherwise’ shall be exclusively on You. We as a merchant shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly owing to the decline of authorisation for any Transaction, on account of the Cardholder having exceeded the pre-set limit mutually agreed between us and our banking partner Axis Bank Limited from time to time. </p>
       <h5 class="mt-3">Fraudulent/Declined Transactions</h5>
       <p>GNOA reserves the right to recover the cost of goods, collection charges and lawyers’ fees from persons using the Site fraudulently. GNOA reserves the right to initiate legal proceedings against such persons for fraudulent use of the Site and any other unlawful acts or acts or omissions or commission in breach of these Terms and Conditions. </p>
       <h5 class="mt-4">You Agree and Confirm</h5>
       <ul class="product-li">
         <li>That In The Event That A Non-Delivery Occurs On Account Of A Mistake By You (I.E. Wrong Name Or Address Or Any Other Wrong Information) Any Extra Cost Incurred By GNOA For Redelivery Shall Be Claimed From You By Our Logistics Partner to GNOA</li>
         <li>That You Will Use The Services Provided By GNOA And Contracted Companies, For Lawful Purposes Only And Comply With All Applicable Laws And Regulations While Using The Site And Transacting On The Site.</li>
         <li>You Will Provide Authentic And True Information In All Instances Where Such Information Is Requested Of You. GNOA Reserves The Right To Confirm And Validate The Information And Other Details Provided By You At Any Point Of Time. If Upon Confirmation Your Details Are Found Not To Be True (Wholly Or Partly), GNOA Has The Right In Its Sole Discretion To Reject The Registration And Debar You From Using The Services Of GNOA Or Other Affiliated Websites Without Prior Intimation Whatsoever.</li>
       </ul>
       <h5 class="mt-3">Use of Platform</h5>
       <p>You agree, undertake and confirm that Your use of Platform shall be strictly governed by the following binding principles:</p>
       <p>You shall not host, display, upload, modify, publish, transmit, update or share any information which: </p>
       <ul class="product-li">
         <li>Belongs To Another Person And In Which The User Does Not Have Any Right To;</li>
         <li>It Is Grossly Harmful, Harassing, Blasphemous, Defamatory, Obscene, Pornographic, Paedophilic, Libellous, Invasive Of Another’s Privacy, Hateful, Or Racially, Ethnically Objectionable, Disparaging, Relating Or Encouraging Money Laundering Or Gambling, Or Otherwise Unlawful In Any Manner Whatsoever;</li>
         <li>Harms Minors In Any Way;</li>
       </ul>
       <h5 class="mt-3">Objectionable Material</h5>
       <p>You understand that by using this site, you may encounter Content that may be deemed by some to be offensive, indecent, or objectionable, which Content may or may not be identifiable as such. You agree to use the Site and any service at your sole risk and that to the fullest extent permitted under the applicable law. GNOA and its affiliates shall incur no liability or responsibility for Content that may be deem offensive, indecent, or objectionable to you.</p>
       <h5 class="mt-3">Payment Services</h5>
       <p>We have availed the services of Axis Bank Limited as our payment gateway partners/banking partners. We as a merchant shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly out of the decline of authorization for any Transaction, on Account of the Cardholder having exceeded the preset limit mutually agreed between us and acquiring bank from time to time. COD will not be available as a ‘mode of payment’. Axis Bank Limited payment gateway has also authorized payments to be received in all currencies and to be converted in INR for purchases made. </p>
       <h5 class="mt-3">User Account Data</h5>
       <ul class="product-li">
         <li>GNOA Respects The Privacy Of Every Inpidual. We Protect The Personal Information In Accordance With Our Privacy Policy And Respect The Confidentiality Of Our Visitors And Subscribers.</li>
         <li>We Share Only The Necessary Information For Processing The Order(S) To Our Trusted Logistics Partner.</li>
         <li>Inpidual Users Are Also Responsible For Maintaining The Confidentiality And Security Of Their Account And Password And You Agree To Accept The Responsibility For All The Activities That Occur Using Your Account And Password.</li>
       </ul>
       <h5 class="mt-3">Governing laws</h5>
       <p>Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. Any disputes rising in relation there to shall be subject to exclusive jurisdiction of the courts in Mumbai. </p>
       <h5 class="mt-3">Jurisdictional Issues/Sale in India Only</h5>
       <p>We trade, all the products directly from our authorized Distribution Chanel network of all respective Sellers. Unless otherwise specified, the material on GNOA is presented solely for the purpose of sale in India. GNOA makes no representation that materials in the Platform are appropriate or available for use in other locations/Countries other than India. Those who choose to access this site from other locations/Countries other than India do so on their own initiative and GNOA is not responsible for supply of products/refund for the products ordered from other locations/Countries other than India, compliance with local laws, if and to the extent local laws are applicable. We accept orders from outside India (deliverable in India Only). </p>
       <h5 class="mt-3">Trademark, Copyright and Restriction</h5>
       <p>All other trademarks, product names, and company names or logos cited herein are the property of their respective owners/sellers/company/brand. You must not reproduce, perform, create derivative works from, republish, upload, post, transmit, or distribute in any way whatsoever any Materials from the Site without prior written permission. </p>
       <p>Without the prior written consent of the owner, modification of the materials, use of the materials on any other Platform or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. </p>
       <h5 class="mt-3">Disclaimer</h5>
       <p>It is the customer’s responsibility to login earlier if they want to avail better products or styles because GNOA sales (if any) are “first come, first served”. The merchandise might not be restocked once sold out. No information regarding the presence of any product in our stock will be guaranteed and we will alert you only when an item is sold out. </p>
       <p>GNOA will not be responsible or liable for any special, incidental, indirect or consequential damages of any kind in connection with this Terms of Use, products purchased and orders cancelled, even if We have been informed in advance. The products procured may not meet customer’s expectation to its minutest details. </p>
       <h5 class="mt-3">Parent Portal Information</h5>
       <p>This ‘Portal’ is exclusively designed and access is based on “UNIQUE ID of the School” for the selective/collaborative schools only.</p>
       <p>The data (i.e. Name of the Child, Standard and pision, GR. No., UID and school email ID is shared by the respective school for distribution of notebooks (and/or other products bought) at the commencement of every academic year.</p>
       <p>We at GNOA will not leak, share, publish and sell any of the confidential data for other promotions or to third party services.</p>
       <p>We at GNOA request for mobile number, address and email for invoice purpose only. In case the respective the parents opt for a ‘Shipping’ option for delivery of the notebooks (and/or other products bought), which is a prerequisite for the books to be delivered via our logistics partner.</p>
       <h5 class="mt-3">Textbook Information</h5>
       <p>All the information mentioned in our website GNOA regarding the Textbook such has ISBN, Title name, Author/s, Publisher and MRP have been collated from the catalog/s (all publishers’ title sold here) shared with by them with us. All the Textbooks are procured through the authorized distribution network through our channel vendor/s.</p>
       <p>None of the title/s is reprint, copied, duplicated or obtained to harm/ disrespect the goodwill of the respective Author/s or Publisher/s.</p>
       <h5 class="mt-3">Dispatch Time</h5>
       <p>We take maximum care to provide timely support for students so that Text books are dispatched on time and the curriculum does not suffer. However Text book titles may / may not be updated on the website at the time when the orders are received. In the event of shortfall in the stocks, it may take up to 10 working days to procure the same. GNOA will not be held liable or responsible if there is delay on the part of the publishers in printing the books.</p>
       <h5 class="mt-3">Contact Us</h5>
       <p>Please contact us for any questions or comments (including all inquiries unrelated to copyright infringement) regarding this Platform.</p>
       <h5 class="mt-3">Grievance officer</h5>
       <p>In accordance with Information Technology Act, 2000 and rules made there under the Consumer Protection (E-Commerce) Rules, 2020 and Information Technology (Guidelines For Intermediaries And Digital Media Ethics Code) Rules 2021 the name and contact details of the Grievance Officer are provided below:</p>
       <h5 class="mt-3">MRP Policy’s</h5>
       <ul class="product-li">
         <li>The Maximum Retail Price (MRP) of each product or service is clearly displayed on the invoice or bill.</li>
         <li>Any charges made over and above the MRP will be adjusted in the next bill or invoice.</li>
         <li>Customers are encouraged to verify the MRP before making a purchase or availing of a service.</li>
       </ul>
       <p>Please note that these terms and conditions are provided as an example only, and may vary depending on the specific context and applicable laws and regulations in your jurisdiction. It is recommended that you consult with a legal professional or your organisation's legal team to ensure compliance with all relevant laws and regulations.</p>
       <p>Contact Person: - </p>
       <p>Contact Email: - support@gnoa.in</p>
       <p>Contact Number: - +91-9137589497</p>
       <p>Time: - 10am to 10pm</p>
     </div>
   </div>
 </section>

    @endsection